#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yappi
Version  : 0.99
Release  : 1
URL      : https://files.pythonhosted.org/packages/18/55/6a30d07853f06ede3df160ed7ce47eb635d0ac7ee5c2e308f4cd61de46cd/yappi-0.99.tar.gz
Source0  : https://files.pythonhosted.org/packages/18/55/6a30d07853f06ede3df160ed7ce47eb635d0ac7ee5c2e308f4cd61de46cd/yappi-0.99.tar.gz
Summary  : Yet Another Python Profiler
Group    : Development/Tools
License  : MIT
Requires: yappi-bin = %{version}-%{release}
Requires: yappi-python = %{version}-%{release}
Requires: yappi-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : nose

%description
# Yappi
**Y**et **A**nother **P**ython **P**rof**i**ler, but this time support Multithread/CPU time profiling.

%package bin
Summary: bin components for the yappi package.
Group: Binaries

%description bin
bin components for the yappi package.


%package python
Summary: python components for the yappi package.
Group: Default
Requires: yappi-python3 = %{version}-%{release}

%description python
python components for the yappi package.


%package python3
Summary: python3 components for the yappi package.
Group: Default
Requires: python3-core

%description python3
python3 components for the yappi package.


%prep
%setup -q -n yappi-0.99

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550540184
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/yappi

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
